### ISSUE TITLE
Some Icons are not generated correctly

### ISSUE THREAD

**Issue by luxbe** [indaco/svelte-iconoir#30]
Some icons do not show up at all. For example the apple-shortcuts.svg results in the following invalid generation:

```svelte
<svg ...>
    <path clip-path="url(#clip0_3190_17433)" /> <path />
</svg>
```

This is because of the `buildIconDataString` method, where it is assumed that only `path` elements are present in the iconoir svgs. It would probably be better to copy the whole svg contents.

**Comment by luxbe** [comment]
I think the [apple-shortcut.svg](https://github.com/iconoir-icons/iconoir/blob/main/icons/apple-shortcuts.svg?short_path=524531d) is declared weirdly by including an useless `clipPath` in its declaration. Would you agree? If so, I would open an issue with iconoir then. But I still believe `svelte-iconoir` should handle these edge cases

**Comment by indaco** [comment]
@luxbe thanks for reporting this 

Agree `svelte-iconoir` has to handle edge cases for sure. 

Would be great to hear from `iconoir` maintainer how big is the edge cases bucket or it is very limited and by mistake. 

Are you willing to help with this?
Thanks

**Comment by luxbe** [comment]
I already checked and there are more than 20 icons where a clipPath is present. There may be more icons with different inconsistencies.

I will open a PR with iconoir to keep the icon declarations consistent and remove useless clipPaths, but in my opinion `svelte-iconoir` should copy the whole svg contents instead of trying to parse them.
What do you think?

**Comment by indaco** [comment]
Agree with you 100%

I used this approach testing it against 250+ icons at that time and thought was a good case

**Comment by indaco** [comment]
Will work on it over the weekend
