### ISSUE TITLE
PrivacypolicyIcon name incorrectly formatted

### ISSUE THREAD

**Issue by luxbe** [indaco/svelte-iconoir#35]
I just noticed that the PrivacypolicyIcon is incorrectly formatted. It should have a capital P in policy, so: PrivacyPolicyIcon to stay consistent with other Icons. Maybe this is also an inconsistency with the upstream iconoir project, and not with the name generation is this project.

**Comment by indaco** [comment]
The original one is "privacy policy.svg"

![image](https://github.com/indaco/svelte-iconoir/assets/13519/e9908c91-0e34-45a4-9a80-be797bd52a2f)

It seems to be the only one (or one of few) without the dash char

Will ask if it is a mistake or not

**Comment by indaco** [comment]
https://github.com/iconoir-icons/iconoir/issues/371

**Comment by indaco** [comment]
fixed in #36
