### ISSUE TITLE
Failed to import but successfully used

### ISSUE THREAD

**Issue by PremaNandika** [indaco/svelte-iconoir#46]
<img width="939" alt="image" src="https://github.com/indaco/svelte-iconoir/assets/48142149/6e2d7243-68a2-4d4c-8de5-8d23aa0a8a5f">

When importing the icon an error occurs as follows, but the icon can still be used.

**Comment by indaco** [comment]
@PremaNandika thanks for reporting it. Will have a look

Which version are you using?

**Comment by indaco** [comment]
@PremaNandika fixed with the latest`v6.0.3`
Thanks
