### ISSUE TITLE
Customizing all SVG properties

### ISSUE THREAD

**Issue by rbozan** [indaco/svelte-iconoir#8]
The current implementation does not allow to customize any SVG property, for my use case: `x` and `y`

https://github.com/indaco/svelte-iconoir/blob/60cd5755e6c86888ce08585c83abe2c471c48c20/scripts/buildIconsDataset.ts#L177-L191

Allowing these svg properties to be set make it possible to embed these SVGs into other SVGs as inline SVG, like so: https://stackoverflow.com/a/27546213

**Comment by indaco** [comment]
> The current implementation does not allow to customize any SVG property, for my use case: `x` and `y`
> 
> https://github.com/indaco/svelte-iconoir/blob/60cd5755e6c86888ce08585c83abe2c471c48c20/scripts/buildIconsDataset.ts#L177-L191
> 
> Allowing these svg properties to be set make it possible to embed these SVGs into other SVGs as inline SVG, like so: [stackoverflow.com/a/27546213](https://stackoverflow.com/a/27546213)

**Comment by indaco** [comment]
@rbozan  release `v4.7.0` added this. 

Thanks to @luxbe for that
